name: Daily Data Ingestion

# Controls when the action will run. In this case, it's scheduled to run daily at 1 AM UTC.
on:
  schedule:
    - cron: '0 15 * * *'  # This cron expression runs the job daily at 01:00 AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  # The latest version of Ubuntu will be used as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # This step checks out your repository so the workflow can access the script.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # This step installs the required Python packages defined in your `requirements.txt` file.

      - name: Run Data Ingestion Script
        run: |
          python data_ingestion.py
        # This step runs your data ingestion script. Make sure to replace `path/to/your/` with the actual path.

      - name: Verify Upload Success
        run: echo "Data ingestion completed successfully."
        # You can add custom messages or steps here to verify that the script ran successfully.
